#!/bin/bash
#
# kausta sisu väljastamine
#
#sisestame kausta asukoht
#echo -n "sisesta kataloogi asukoht süsteemis :"
# read kaust
kaust=$1
#
for nimi in $(ls $kaust)
do
if [ -f "$nimi" ]; then
echo "$nimi"
fi
done
