#!/bin/bash
#
# kella ja kalendri väljastamine
#
# defineerime vajalikud muutujad
kuupaev=$(date +"%A, %B %d, %Y")
kell=$(date +"%H:%M")
# koostame väljatrükk
echo "today is $kuupaev"
echo # tühi rida
echo "Time is $kell"
echo
# jälle vajalik muutuja
kuu=$(date +"%B %Y")
echo "Calendar of $kuu"
echo "===================="
# kalendri muutuja
cal | tail -n 7
echo "===================="
